name: PackSquash
on: [push]

jobs:
  PackSquash:
    strategy:
      matrix:
        pack: [ vanilla, cartoon, chinese-mythology, city, fallout, fantasy, festive, greek-mythology, halloween, natural, plastic, steampunk,]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          artifact_name: ${{ matrix.pack }}
          options: |
            pack_directory = './Packs/${{ matrix.pack }}'