name: PackSquash
on: [push]

jobs:
  PackSquash:
    strategy:
      matrix:
        pack: [ vanilla, cartoon, chinese-mythology, city, fallout, fantasy, festive, greek-mythology, halloween, natural, plastic, steampunk,]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run PackSquash
        working-directory: ./Packs
        uses: ComunidadAylas/PackSquash-action@v4
        with:
        packsquash_version: latest
        artifact_name: ${{ matrix.pack }}
        options: |
          pack_directory = '${{ matrix.pack }}'
          output_file_path = 'out/${{ matrix.pack }}.zip'